// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chart_pattern_signal.proto

package com.altfins;

public interface ChartPatternSignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:altfins.ChartPatternSignal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Example BTCUSDT
   * </pre>
   *
   * <code>string coin_pair = 1;</code>
   */
  java.lang.String getCoinPair();
  /**
   * <pre>
   * Example BTCUSDT
   * </pre>
   *
   * <code>string coin_pair = 1;</code>
   */
  com.google.protobuf.ByteString
      getCoinPairBytes();

  /**
   * <pre>
   * Name of the pattern.
   * </pre>
   *
   * <code>string pattern = 2;</code>
   */
  java.lang.String getPattern();
  /**
   * <pre>
   * Name of the pattern.
   * </pre>
   *
   * <code>string pattern = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatternBytes();

  /**
   * <pre>
   * If false, it is an emerging signal.
   * </pre>
   *
   * <code>bool is_breakout = 3;</code>
   */
  boolean getIsBreakout();

  /**
   * <code>.altfins.TimeFrame time_frame = 4;</code>
   */
  int getTimeFrameValue();
  /**
   * <code>.altfins.TimeFrame time_frame = 4;</code>
   */
  com.altfins.TimeFrame getTimeFrame();

  /**
   * <pre>
   * The price at breakout, avaialble in some types of patterns such as breaking resistance and support.
   * </pre>
   *
   * <code>double breakout_price = 5;</code>
   */
  double getBreakoutPrice();

  /**
   * <code>double target_price = 6;</code>
   */
  double getTargetPrice();

  /**
   * <pre>
   * The target time for the signal in Epoch seconds.
   * </pre>
   *
   * <code>int64 target_time_secs = 7;</code>
   */
  long getTargetTimeSecs();

  /**
   * <code>.altfins.TradeType trade_type = 8;</code>
   */
  int getTradeTypeValue();
  /**
   * <code>.altfins.TradeType trade_type = 8;</code>
   */
  com.altfins.TradeType getTradeType();

  /**
   * <pre>
   * "xx minutes/hours/days ago"
   * </pre>
   *
   * <code>string breakout_time = 9;</code>
   */
  java.lang.String getBreakoutTime();
  /**
   * <pre>
   * "xx minutes/hours/days ago"
   * </pre>
   *
   * <code>string breakout_time = 9;</code>
   */
  com.google.protobuf.ByteString
      getBreakoutTimeBytes();
}
