// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chart_pattern_signal.proto

package com.altfins;

public final class ChartPatternSignalOuterClass {
  private ChartPatternSignalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_altfins_ChartPatternSignal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_altfins_ChartPatternSignal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032chart_pattern_signal.proto\022\007altfins\"\345\001" +
      "\n\022ChartPatternSignal\022\021\n\tcoin_pair\030\001 \001(\t\022" +
      "\017\n\007pattern\030\002 \001(\t\022\023\n\013is_breakout\030\003 \001(\010\022&\n" +
      "\ntime_frame\030\004 \001(\0162\022.altfins.TimeFrame\022\026\n" +
      "\016breakout_price\030\005 \001(\001\022\024\n\014target_price\030\006 " +
      "\001(\001\022\030\n\020target_time_secs\030\007 \001(\003\022&\n\ntrade_t" +
      "ype\030\010 \001(\0162\022.altfins.TradeType*G\n\tTimeFra" +
      "me\022\017\n\013FIFTEEN_MIN\020\000\022\014\n\010ONE_HOUR\020\001\022\016\n\nFOU" +
      "R_HOURS\020\002\022\013\n\007ONE_DAY\020\003*\036\n\tTradeType\022\007\n\003B" +
      "UY\020\000\022\010\n\004SELL\020\001B\017\n\013com.altfinsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_altfins_ChartPatternSignal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_altfins_ChartPatternSignal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_altfins_ChartPatternSignal_descriptor,
        new java.lang.String[] { "CoinPair", "Pattern", "IsBreakout", "TimeFrame", "BreakoutPrice", "TargetPrice", "TargetTimeSecs", "TradeType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
