// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chart_pattern_signal.proto

package com.altfins;

/**
 * Protobuf enum {@code altfins.TimeFrame}
 */
public enum TimeFrame
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FIFTEEN_MIN = 0;</code>
   */
  FIFTEEN_MIN(0),
  /**
   * <code>ONE_HOUR = 1;</code>
   */
  ONE_HOUR(1),
  /**
   * <code>FOUR_HOURS = 2;</code>
   */
  FOUR_HOURS(2),
  /**
   * <code>ONE_DAY = 3;</code>
   */
  ONE_DAY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FIFTEEN_MIN = 0;</code>
   */
  public static final int FIFTEEN_MIN_VALUE = 0;
  /**
   * <code>ONE_HOUR = 1;</code>
   */
  public static final int ONE_HOUR_VALUE = 1;
  /**
   * <code>FOUR_HOURS = 2;</code>
   */
  public static final int FOUR_HOURS_VALUE = 2;
  /**
   * <code>ONE_DAY = 3;</code>
   */
  public static final int ONE_DAY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TimeFrame valueOf(int value) {
    return forNumber(value);
  }

  public static TimeFrame forNumber(int value) {
    switch (value) {
      case 0: return FIFTEEN_MIN;
      case 1: return ONE_HOUR;
      case 2: return FOUR_HOURS;
      case 3: return ONE_DAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TimeFrame>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TimeFrame> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TimeFrame>() {
          public TimeFrame findValueByNumber(int number) {
            return TimeFrame.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.altfins.ChartPatternSignalOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final TimeFrame[] VALUES = values();

  public static TimeFrame valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TimeFrame(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:altfins.TimeFrame)
}

